name: Build

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:

jobs:
  build:
    name: Build `nxjs.nro`
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build QuickJS
        working-directory: ./lib/quickjs
        run: make

      - name: Build nx.js
        run: make
      
      - run: ls -l